# Generated by Django 3.1.7 on 2021-02-25 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.AutoField(db_column='locationid', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Location',
                'unique_together': {('locationid', 'name')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('profile_photo', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=45)),
            ],
            options={
                'db_table': 'User',
                'unique_together': {('userid', 'first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='TripInstance',
            fields=[
                ('tripinstanceid', models.AutoField(db_column='tripinstanceid', primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'TripInstance',
                'unique_together': {('tripinstanceid', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('tripid', models.AutoField(db_column='tripid', primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('tripinstance_tripinstanceid', models.ForeignKey(db_column='tripinstance_tripinstanceid', on_delete=django.db.models.deletion.CASCADE, to='alldata.tripinstance')),
            ],
            options={
                'db_table': 'Trip',
                'unique_together': {('tripid', 'tripinstance_tripinstanceid')},
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guideid', models.AutoField(db_column='guideid', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Guide',
                'unique_together': {('guideid', 'first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='UserBuysTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_tripid', models.ForeignKey(db_column='trip_tripid', on_delete=django.db.models.deletion.CASCADE, to='alldata.trip')),
                ('user_userid', models.ForeignKey(db_column='user_userid', on_delete=django.db.models.deletion.CASCADE, to='alldata.user')),
            ],
            options={
                'db_table': 'UserBuysTrip',
                'unique_together': {('user_userid', 'trip_tripid')},
            },
        ),
        migrations.CreateModel(
            name='LocationOfTripInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_locationid', models.ForeignKey(db_column='location_locationid', on_delete=django.db.models.deletion.CASCADE, to='alldata.location')),
                ('tripinstance_tripinstanceid', models.ForeignKey(db_column='tripinstance_tripinstanceid', on_delete=django.db.models.deletion.CASCADE, to='alldata.tripinstance')),
            ],
            options={
                'db_table': 'LocationOfTripInstance',
                'unique_together': {('location_locationid', 'tripinstance_tripinstanceid')},
            },
        ),
        migrations.CreateModel(
            name='GuideLeadsTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_tripid', models.ForeignKey(db_column='trip_tripid', on_delete=django.db.models.deletion.CASCADE, to='alldata.trip')),
                ('user_userid', models.ForeignKey(db_column='user_userid', on_delete=django.db.models.deletion.CASCADE, to='alldata.user')),
            ],
            options={
                'db_table': 'GuideLeadsTrip',
                'unique_together': {('user_userid', 'trip_tripid')},
            },
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('bankcardid', models.AutoField(db_column='bankcardid', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('valid_date', models.DateField()),
                ('number', models.BigIntegerField()),
                ('cvv', models.IntegerField()),
                ('user_userid', models.ForeignKey(db_column='user_userid', on_delete=django.db.models.deletion.CASCADE, to='alldata.user')),
            ],
            options={
                'db_table': 'BankCard',
                'unique_together': {('bankcardid', 'name', 'user_userid')},
            },
        ),
    ]
